---
title: "NDVI2018"
author: "Henry"
date: "July 11, 2018"
output: html_document
---

```{r datainput and setup}
library(ggplot2)
library(reshape2)
#data input
library(xlsx)
ndvi <- read.xlsx("C:/Users/henry/Dropbox/Projects/ROS papers/Quantile Regression Manuscript/data/2017 Rainout Shelter Field Plan.xlsx",2) 
#drop unnecessary columns
ndvi <- ndvi[,-c(1,4,5,8)]
#reshape data into long format
df <- melt(ndvi, id = c("Rep","Entry"))
colnames(df) <- c("rep","entry","date","ndvi")
df$date <- gsub("X","",df$date)
df$date <-as.Date(df$date,"%m.%d.%Y")

```

## R Markdown


```{r NDVI}
summary(df)
head(df)
boxplot(df$ndvi~df$date)
```

## population segregation of the three reps

```{r ggplot}
ggplot(df, aes(x=date,y=ndvi))+
  geom_point()+
  #facet_grid(rep~.)+
  geom_quantile(quantiles = c(0.05,0.5,0.95), formula = y ~ poly(x,5))
```

## population distribution change over time

```{r ggplot:population distribution change}
ggplot(df,aes(x= ndvi))+
  geom_density()+
  facet_grid(date~.)
```